### ISSUE TITLE
Pls provide editable sources for all assets (such as architecture in .PNG etc)

### ISSUE THREAD

**Issue by renatco** [Atomica-Core/KeeperPool#2]
Would like to contribute and propose improvements, but cant edit png.

**Comment by renatco** [comment]
Perhaps URL to a source in google app (such as Google Drawings or Google Slide for charts) to ensure collaborative work.

**Comment by elenat** [comment]
> Perhaps URL to a source in google app (such as Google Drawings or Google Slide for charts) to ensure collaborative work.

Image source added https://drive.google.com/file/d/1mllT3itzyakz_S_rpPr5LxlgyQmODqqM/view?usp=sharing
